package com.hansung.capstone

object Constants {
    const val ACTION_CREATE_SERVICE = "ACTION_CREATE_SERVICE"
    const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"

    const val NOTIFICATION_CHANNEL_ID = "RIDING_CHANNEL_ID"
    const val NOTIFICATION_CHANNEL_NAME = "RIDING_CHANNEL"
    const val NOTIFICATION_ID = 1

}